### ISSUE TITLE
install/update wordPress plugins without providing FTP access

### ISSUE THREAD

**Issue by edouardb** [online-labs/image-app-wordpress#4]
Add the following to the wp-config.php file to solve the problem:

define('FS_METHOD', 'direct');

**Comment by moul** [comment]
![](https://www.dropbox.com/s/75rb3sqxz6kv8ea/Screenshot%202015-02-09%2016.49.37.png?dl=1)![](https://www.dropbox.com/s/75rb3sqxz6kv8ea/Screenshot%202015-02-09%2016.49.37.png?dl=1)

**Comment by moul** [comment]
Fixed upgrade and package install

![](https://www.dropbox.com/s/vzyy20gjwiqseib/Screenshot%202015-02-09%2017.10.28.png?dl=1)

![](https://www.dropbox.com/s/vmulzkbksluyayi/Screenshot%202015-02-09%2017.11.23.png?dl=1)
